### ISSUE TITLE
Create movie from data stream instead of filename

### ISSUE THREAD

**Issue by quattro004** [streamio/streamio-ffmpeg#100]
Is there a way that I can call FFMPEG::Movie.new with a data stream instead of a filename? Basically I want to generate a thumbnail from a video while it's being uploaded to my rails site. The file doesn't exist as the user is still uploading it and I am saving it to a mysql database instead of the file system. However, I have access to the data stream if that makes sense.

**Comment by iaybar** [comment]
There's a pull request and a discution about it. Check this: https://github.com/streamio/streamio-ffmpeg/pull/54

**Comment by bikeath1337** [comment]
URL as an input stream is supported now on master. will be in the next release.
