### ISSUE TITLE
Use ffprobe instead of ffmpeg

### ISSUE THREAD

**Issue by Mic92** [streamio/streamio-ffmpeg#102]
Parsing the ffmpeg text output is complex an error prone. It is much easier to parse ffprobe output, when using the json option (``-print_format json``). This is at least, what I use in my last project. Just a recommendation of mine.

**Comment by seanabrahams** [comment]
There's a PR from a year ago that switches to using ffprobe: #73

**Comment by bikeath1337** [comment]
This has been implemented in 2.0
