### ISSUE TITLE
Wrong resolution info for some videos

### ISSUE THREAD

**Issue by AndKiel** [streamio/streamio-ffmpeg#104]
Examples of `video_stream` for which resolution info is wrong:

> video_stream: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 22469 kb/s, 120.16 fps, 2400 tbr, 2400 tbn, 4800 tbc (default)
> resolution: bt709)

> video_stream: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 640x360, 2826 kb/s, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 2500 tbn, 50 tbc (default)
> resolution: smpte170m)

Problem is the colorspace having additional info in parentheses.

**Comment by abaraka** [comment]
It's fixed here: a9db9679adbad5752d43d9f3dd34356af72198af but I had to use

`gem 'streamio-ffmpeg', git: 'https://github.com/streamio/streamio-ffmpeg.git'`
