### ISSUE TITLE
How to hide streamio-ffmpeg dumpling information on terminal

### ISSUE THREAD

**Issue by makodoben** [streamio/streamio-ffmpeg#105]
Hi All~

  When I running the testing to get video file to compare the latest previous video file. 
There dumping the information on terminal. It look like no big deal.

But if  I fetch the video used this method:

         'let(:resource) { create :resource, :file => File.new("#{Rails.root}/spec/fixtures/xx.mp4") }'

And give some test logic code like this:

        'it {expect(resource.width).to eq 640}'
        'it {expect(resource.height).to eq 428}'

  It will be duplicate dumpling below information twice by the above two ‘it' block description code.
**What should I do if I want to hide those redundant information on terminal completely?
Have Any Good Ideas?**	
***
                                   The streamio-ffmpeg dumpling information
Run options: include {:locations=>{"./spec/models/resource_spec.rb"=>[11]}}
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.7.2_1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/folders/rv/t962rfpn1799m819d5qw3_wr0000gn/T/5e8ff9bf55ba3508199d22e984129be620150902-38041-vlxbfk.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2015-08-17 14:11:30
    encoder         : Lavf52.62.0
    comment         : FlixEngine_8.1.0.2
  Duration: 00:00:09.60, start: 0.000000, bitrate: 750 kb/s
…
…
...
[swscaler @ 0x7f903300a200] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/var/folders/rv/t962rfpn1799m819d5qw3_wr0000gn/T/5e8ff9bf55ba3508199d22e984129be620150902-38041-vlxbfk20150902-38041-e644hi.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    comment         : FlixEngine_8.1.0.2
    encoder         : Lavf56.36.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 192x192, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2015-08-17 14:11:30
      handler_name    : VideoHandler
      encoder         : Lavc56.41.100 jpeg

**Comment by gustavosobral** [comment]
Any news? Have you solved this @makodoben? I would like to suppress streamio log on test enviroment

**Comment by bikeath1337** [comment]
The FFMpeg gem specs change the logger in https://github.com/streamio/streamio-ffmpeg/blob/master/spec/spec_helper.rb#L6.

Add that line to your own `spec_helper.rb`.

**Comment by gustavosobral** [comment]
Thank you @bikeath1337 !
