### ISSUE TITLE
`FFMPEG::Movie.new(path)` errors not being surfaced

### ISSUE THREAD

**Issue by benwalsh** [streamio/streamio-ffmpeg#107]
* Setting `path` of something like `/tmp/Rampaging+Ocelot20150923-7319-af1aq3.mov`

* Running `FFMPEG::Move.new(path)` would "hang" indefinitely with no output in Ruby console, logs, etc.

* Running `ps auxw` would show this:
```
owner     xxxx  0.0  0.0   xxxx   xxxx ?        S    16:03   0:00 sh -c /usr/bin/ffprobe -i /tmp/Rampaging+Ocelot20150923-7319-af1aq3.mov -print_format json -show_format -show_streams -show_error
owner     xxxx  0.0  0.4 xxxx xxxx ?        S    16:03   0:00 /usr/bin/ffprobe -i /tmp/Rampaging+Ocelot20150923-7319-af1aq3.mov -print_format json -show_format -show_streams -show_error
```

* Those tasks would also show indefinitely.

* Running that task as `sudo` from the command line directly would show the error -- `ffprobe` does not like the filename:

```
/tmp/Rampaging+Ocelot20150923-7319-af1aq3.mov: No such file or directory
    "error": {
        "code": -2,
        "string": "No such file or directory"
    }
}
```

* Changing the filename to something without reserved URL characters (eg. `/tmp/rampaging_ocelot.mov` or a `SecureRandom.uuid`) and it works fine.

* It would be preferred if it raised an error for a filename it can't process!

**Comment by bikeath1337** [comment]
I just volunteered to get some movement on this project. Thanks for the ticket. Be patient while we get up to speed.
