### ISSUE TITLE
How to disable FFMPEG logger?

### ISSUE THREAD

**Issue by u0x01** [streamio/streamio-ffmpeg#115]
Sometimes there will be such a task is terminated due to an error

        Input/output error @ io_write - <STDERR>

After the restart the resque and retry tasks will can be return to work.

Here's my task code:

      transcode_cmd =  %Q(-threads 0 )

      transcode_cmd << %Q(-codec:v libx264 )

      transcode_cmd << %Q(-vf scale="#{resolution}:trunc(ow/a/2)*2" )

      transcode_cmd << %Q(-f hls -hls_allow_cache 1 )

      transcode_cmd << %Q(-hls_time 10 -hls_list_size 0 )

      transcode_cmd << %Q(-hls_key_info_file "#{key_info_file}" )

      transcode_cmd << %Q(-hls_base_url "//endpoint/" )

      transcode_cmd <<  %Q(-hls_segment_filename "#{output_m3u8_dir}/stream%03d" )

      movie = FFMPEG::Movie.new(video.filename)

      movie.transcode(output_m3u8, transcode_cmd, validate: false) do |progress|
        video_file.update_attribute :progress, progress*10000
        Rails.logger.debug "transcoding #{file_basename}:#{resolution}p in: #{progress*100}"
      end

I found out this err is from logger, How to disable logger?

**Comment by bikeath1337** [comment]
Refer to answer in #105 .
