### ISSUE TITLE
`FFMPEG::Movie` marks any file with a data stream as invalid

### ISSUE THREAD

**Issue by codekitchen** [streamio/streamio-ffmpeg#116]
The definition of `valid?` is too simplistic, if you hand it a valid movie file that also has a 3rd `"codec_type": "data"` stream, it'll match the text `"Unsupported codec"` in stderr and mark the whole file as invalid. See https://github.com/streamio/streamio-ffmpeg/blob/master/lib/ffmpeg/movie.rb#L93

It seems like the concept of validity should be based on the file having at least one supported audio or video stream, but I'm not completely sure how that should look yet.

**Comment by bikeath1337** [comment]
Why don't you mull it over and come up with some suggestions. Thanks!

**Comment by codekitchen** [comment]
I see a few different options:

* Add the `-select-streams u` option to the ffprobe call, which would tell fprobe to filter the output to only usable audio and video streams. This means we lose some potentially interesting information in the output about the data streams, but that seems OK for this Class since it doesn't currently hold on to the raw output information anyway.
* Remove the `"Unsupported codec"` match on line 93, which would match the behavior of this class before the switch to using ffprobe. Data streams will be silently ignored. However, it probably makes the `valid?` method less useful when an actual unsupported video/audio codec is input.
* Remove line 93, but add validation logic to ensure the codec is defined and has its basic audio/video parameters in place. This option is the most flexible but also error prone.

**Comment by canadaduane** [comment]
The output on stderr does give us the necessary info to map the "Unsupported codec" message back to the actual stream(s) causing the issue:

```Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/o-4UTCxry9ac531WsFoiPVkjaB1zAyyCX1':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2016-01-28 01:32:02
  Duration: 00:03:23.55, start: 0.000000, bitrate: 17265 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 17149 kb/s, 29.98 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2016-01-28 01:32:02
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 87 kb/s (default)
    Metadata:
      creation_time   : 2016-01-28 01:32:02
      handler_name    : Core Media Data Handler
    Stream #0:2(und): Data: none (mebx / 0x7862656D), 19 kb/s (default)
    Metadata:
      creation_time   : 2016-01-28 01:32:02
      handler_name    : Core Media Data Handler
    Stream #0:3(und): Data: none (mebx / 0x7862656D) (default)
    Metadata:
      creation_time   : 2016-01-28 01:32:02
      handler_name    : Core Media Data Handler
Unsupported codec with id 0 for input stream 2
Unsupported codec with id 0 for input stream 3
```

Perhaps we could be a little smarter about pulling out those id and stream numbers, then include them in the metadata itself? Followed by a more intelligent validation that checks to see if the unsupported codecs are associated with the video/audio streams.

**Comment by codekitchen** [comment]
It appears that the `-select_streams u` option was added in ffmpeg/ffprobe `2.8.x`, it's not available in `2.6.x`, so the first option I presented probably isn't a good route to go.

**Comment by canadaduane** [comment]
Solution we're working with: https://github.com/canadaduane/rlovelett-ffmpeg/commit/dfc2b7c9fd0413a0634a685f3fc967a527766644

**Comment by gmcnaughton** [comment]
@canadaduane Thanks for the patch, we're running that in production and it's working well!

**Comment by canadaduane** [comment]
Great! Glad it's working for you as well.

On Tue, Jul 12, 2016 at 3:58 AM, Gordon McNaughton <notifications@github.com

**Comment by raulccabreu** [comment]
Are two PR #123 and #131 that fixes this. While the official streamio don't merge one of this, i'm working on production with d4rky-pl/streamio-ffmpeg fork (d9890089cde9514c715369ca584dbdb349de7c56 - #131) and everything is fine until now.

**Comment by bikeath1337** [comment]
The fixes should be on master now, if you'd like to review and try them, please do and let us know. @raulccabreu @canadaduane @gmcnaughton
