### ISSUE TITLE
Audio conversion only -- i.e. wav to mp3

### ISSUE THREAD

**Issue by TrevorHinesley** [streamio/streamio-ffmpeg#120]
Is this possible? I saw a spec that mentioned audio-only conversion, but am unsure how to implement with the current configuration.

**Comment by BlazPerus** [comment]
Is this now possible & how?

**Comment by bikeath1337** [comment]
As my note suggested, please check the specs here: https://github.com/streamio/streamio-ffmpeg/pull/140/files. They provide an example.
