### ISSUE TITLE
JSON error message?

### ISSUE THREAD

**Issue by sixtyfive** [streamio/streamio-ffmpeg#125]
So I was in the desert for a month (literally) so I'm pretty sure my code (or the Gem version, or the FFMPEG version) didn't change, but for some reason, this now happens:

```
$ rails c
Loading production environment (Rails 4.2.6)
[1] pry(main)> ffmpeg = FFMPEG::Movie.new("tmp/recordings/1881.wav")
MultiJson::ParseError: JSON::ParserError
from /usr/local/rvm/gems/ruby-2.3.0@rails42/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load'
[2] pry(main)>
```

Unfortunately I've no clue how to even debug this. FWIW, `1881.wav` is a proper and non-boken WAV file. Any hints or even suggestions to RTFM (just, what part?) would be welcome!

**Comment by kylesziv** [comment]
I'm experiencing this as well. Curious about the resolution.

**Comment by bikeath1337** [comment]
Which gem versions of MultiJson and streamio-ffmpeg are you using?

**Comment by sixtyfive** [comment]
Ever since my original post it's been locked at 1.0.0 as not to break things.

**Comment by makania** [comment]
Having the same issue, running the app in nginx with passenger. The string to be parsed is empty and this is due to reading from stdout (movie.rb, line 22: std_output = stdout.read unless stdout.nil?)

**Comment by phyllisstein** [comment]
I ran into this problem when my Brewed FFMPEG binary broke:

```zsh
~/R/I/volmar ❯❯❯ /usr/local/bin/ffprobe -i spec/fixtures/village.mov -print_format json -show_format -show_streams -show_error # generated by the gem
dyld: Library not loaded: /usr/local/opt/openh264/lib/libopenh264.1.dylib
  Referenced from: /usr/local/bin/ffprobe
  Reason: image not found
[1]    46696 abort      /usr/local/bin/ffprobe -i spec/fixtures/village.mov -print_format json
```

Might make sense to wrap the JSON parsing in a `rescue` block so you can still fail with a useful message and stack trace if there are lower-level errors than expected.

**Comment by phyllisstein** [comment]
PR implementing that suggestion in #134.

**Comment by bikeath1337** [comment]
#134 merged to master.
