### ISSUE TITLE
Failed to create output file on windows if output file is fomat (out%d.png)

### ISSUE THREAD

**Issue by SButterfly** [streamio/streamio-ffmpeg#127]
This error is the continuance of https://github.com/streamio/streamio-ffmpeg/issues/126 issue, but on windows.

If I want output like this on windows:
```ruby
        options = { 
            frame_rate: fps,
            seek_time: start_time,
            duration: duration,
            custom: " -f image2"
        }
        @movie.transcode("frame_%d.png", options)
```
I'll get this command:
```
C:\ffmpeg\bin/ffmpeg.EXE -y -i C:/path/video_05.17.2016_11.33.01.457.mp4 -r 3.0 -ss 0.0 -t 30 -vf crop=720.0:589.0:0.0:345.0 -f image2 C:/path/frame_\%d.png
``` 
which of course fails on windows.

It's due to `Shellwords.escape` method on `FFMPEG:Transcoder.transcode_movie`.

**Comment by SButterfly** [comment]
I've found PR https://github.com/streamio/streamio-ffmpeg/pull/80. Please, accept it.

**Comment by bikeath1337** [comment]
This should be addresed by removing the Shellwords dependency and passing the file paths directly to popen3. These changes are on master now for the next release.
