### ISSUE TITLE
Problem with multiply screenshots

### ISSUE THREAD

**Issue by russo-matrosso** [streamio/streamio-ffmpeg#132]
Maybe I do something wrong, but the following code generates only one screenshot:
`movie.screenshot("screenshot.jpg", vframes: 20, frame_rate: '1/6')`
But, as said in instruction, it should "generate multiple screenshots in a single pass, specify vframes. The following code generates up to 20 screenshots every 10 seconds"

Of course, there is a decision: [https://github.com/streamio/streamio-ffmpeg/issues/126](https://github.com/streamio/streamio-ffmpeg/issues/126)
But to use it, we need to patch ffmpeg gem.

Maybe the README file should be improved? Or I do something wrong?

**Comment by bikeath1337** [comment]
@russo-matrosso  you need to use an output file spec with a wildcard _and_ disable output filename validation. I will correct the documentation to reflect this.

```ruby
movie.screenshot("screenshot_%d.jpg", vframes: 20, frame_rate: '1/6', validate: false)
```

**Comment by russo-matrosso** [comment]
Ok, thank you, this works fine

**Comment by bikeath1337** [comment]
Correction...`validate` is a transcoder option:

```ruby
movie.screenshot("screenshot_%d.jpg", {vframes: 20, frame_rate: '1/6'}, validate: false)
```

**Comment by russo-matrosso** [comment]
Yes, I understood that
