### ISSUE TITLE
transcode complains when given String, asks for a String instead

### ISSUE THREAD

**Issue by chrislerum** [streamio/streamio-ffmpeg#138]
re line: 
https://github.com/streamio/streamio-ffmpeg/blob/master/lib/ffmpeg/transcoder.rb#L25

When I give #transcode options as a String, I get following error:

Unknown options format 'String', should be either EncodingOptions, Hash or String.

**Comment by bikeath1337** [comment]
This should be fixed on master but the way to pass the custom string has changed. It has to be passed as an array like so:

```
custom: %w(-vf crop=60:60:10:10 -map 0:0 -map 0:1)
```

**Comment by bikeath1337** [comment]
Fixed in v3.0.0.
