### ISSUE TITLE
undefined method `=~'

### ISSUE THREAD

**Issue by gcely** [streamio/streamio-ffmpeg#139]
why happened this issue:

undefined method `=~' for #<Pathname:/home/ubuntu/workspace/public/uploads/video/aaa8.mov>
  54678580       /usr/local/rvm/gems/ruby-2.3.0/gems/streamio-ffmpeg-2.1.0/lib/ffmpeg/movie.rb:135:in `remote?'
  54678580       /usr/local/rvm/gems/ruby-2.3.0/gems/streamio-ffmpeg-2.1.0/lib/ffmpeg/movie.rb:18:in `initialize'

**Comment by bikeath1337** [comment]
Looks like you're using a class `Pathname` to initialize the Movie. The pathname should be a String so that the `remote?` method can identify a remote URL or file path.
