### ISSUE TITLE
How to create image with text

### ISSUE THREAD

**Issue by RisingPlay** [streamio/streamio-ffmpeg#152]
ffmpeg -f lavfi -i nullsrc=s=750x60:d=0.01 
-vf "format=rgba,scale,geq='r=255*(X/W):g=255*(Y/H):b=255*((X/W)*(Y/H)):alpha_expr=255*(1-Y/H)', 
format=rgba,drawtext=enable:fontfile=Vera.ttf:textfile=text.txt:fontsize=18:reload=1:y=h/2-line_h/2:x=250 
" -pix_fmt rgba -y txt.png

How to write this code in streamio-ffmpeg rails ?
Please help me.

**Comment by bikeath1337** [comment]
You have to use the transcoder directly because you don't have a movie to work with. Something like this should work:

```ruby
options = { 
  custom: %w(-vf "format=rgba,scale,geq='r=255*(X/W):g=255*(Y/H):b=255*((X/W)(Y/H)):alpha_expr=255(1-Y/H)',format=rgba,drawtext=enable:fontfile=Vera.ttf:textfile=text.txt:fontsize=18:reload=1:y=h/2-line_h/2:x=250"
        -pix_fmt rgba) }
transcoder = FFMPEG::Transcoder.new(
  '', 
  'text.png', 
  options,
  input: 'nullsrc=s=750x60:d=0.01',
  input_options: {f: 'lavfi'})
result = transcoder.run

# Show transcoder command used
puts transcoder.command.join(' ')
```

**Comment by RisingPlay** [comment]
Thank you Sir, that saved my lots of time.
Now it's working!
Although defining custom filters between " " not working without " " is working like this

custom: %w(-vf scale,format=rgba,geq='r=255*(X/W):g=255*(Y/H):b=255*((X/W)*(Y/H)):alpha_expr=255*(1-Y/H)',drawtext=enable:fontfile=Vera.ttf:text='ttffdsf':fontsize=28:y=h/2-line_h/2:x=250 -pix_fmt rgba )

**Comment by bikeath1337** [comment]
Good to hear. I corrected my reply above per your notes.
