### ISSUE TITLE
Speed up screenshots

### ISSUE THREAD

**Issue by d4rky-pl** [streamio/streamio-ffmpeg#159]
Hey, is there any change to revisit [this decision](https://github.com/streamio/streamio-ffmpeg/issues/13#issuecomment-2477311)? It's been 6 years already, I don't believe old MPEG-1 and MPEG-2 codecs are in much use anymore.

If not, is there any way somebody could provide a test file that actually triggers this issue?

**Comment by bikeath1337** [comment]
@d4rky-pl I've not been working on this project for that long...so I can be on the same page...the gem now places the input options before the input file and its Movie now supports a `screenshot` method, which was meant to be optimized so that ffmpeg can do its work, and allows single or multiple screenshots in one pass.

That being said, I believe that ffmpeg's release history has included many optimizations on this matter, so being release current should help. That being said, (you probably know this already), ffmpeg has been optimized to transcode from the nearest previous keyframe, so depending on the keyframe interval, the cost can vary.

So...I thought this issue was addressed, but if it's not, I'd be happy to see what we can improve.

These two merged PRs are related:

https://github.com/streamio/streamio-ffmpeg/pull/133
https://github.com/streamio/streamio-ffmpeg/pull/147

**Comment by d4rky-pl** [comment]
@bikeath1337 I saw that you can pass input options via transcoder options (which btw should in my opinion be merged with encoding options but I'm going to create a separate issue for this later) but it is not used internally which means the default way of creating a screenshot does not use it.

So let's say we want to create a screenshot of the 30th second of the video. Based on README, I'd use this:

```
movie.screenshot("screenshot.jpg", seek_time: 5, resolution: '320x240')
```

and it creates this command to run:

```
["/vagrant/bin/ffmpeg", "-y", "-i", "/home/vagrant/big_buck_bunny.mp4", "-ss", "5", "-s", "320x240", "-vframes", "1", "-f", "image2", "-aspect", "1.3333333333333333", "screenshot.jpg"]
```

The problem here is that if you put the `-ss` command line option before the `-i`, ffmpeg will have to scan the whole file until it gets to this particular point in video and only then snap the keyframe (loglevel added for brevity):

```
vagrant@fraim:/vagrant (master)*$ time /vagrant/bin/ffmpeg -y -i /home/vagrant/big_buck_bunny.mp4 -ss 30 -s 320x240 -vframes 1 -f image2 -aspect 1.3333333333333333 -loglevel fatal screenshot.jpg

real	0m0.566s
user	0m0.764s
sys	0m0.052s
```

While if you put it before `-i`, ffmpeg will try to grab the least amount of data it needs to generate a keyframe:

```
vagrant@fraim:/vagrant (master)*$ time /vagrant/bin/ffmpeg -y -ss 30 -i /home/vagrant/big_buck_bunny.mp4 -s 320x240 -vframes 1 -f image2 -aspect 1.3333333333333333 -loglevel fatal screenshot.jpg

real	0m0.031s
user	0m0.020s
sys	0m0.008s
```

The time difference is even bigger when using remote URLs as input because then ffmpeg has to download everything from the beginning of the file up to the point where you create a screenshot which takes lots of time (especially for longer, larger videos).

The reasoning why `streamio-ffmpeg` does not put `-ss` was [that some old codecs were buggy and sometimes returned gibberish images](https://github.com/streamio/streamio-ffmpeg/issues/13#issuecomment-2477311). This decision has been questioned multiple times before - #32 #33 #40 

I see that you have addressed this a bit in #94 and via #135 but the default `screenshot` option and README still promote the old way without giving sensible alternative (other than passing `input_options` which is not entirely documented and will not be obvious for someone who is not familiar with the problem)

**Comment by bikeath1337** [comment]
Thanks much. i'm aware of the important of positioning the input options, though later versions of ffmpeg have optimizes for that, but for the greatest compatibility, the option should indeed be before the input.

**Comment by d4rky-pl** [comment]
If I understand the [ffmpeg documentation](https://trac.ffmpeg.org/wiki/Seeking) correctly, the buggy behaviour was already addressed many versions ago

> As of FFmpeg 2.1, when transcoding with ffmpeg (i.e. not just stream copying), -ss is now also "frame-accurate" even when used as an input option. Previous behavior (seeking only to the nearest preceding keyframe, even if not precisely accurate) can be restored with the -noaccurate_seek option.

**Comment by d4rky-pl** [comment]
@bikeath1337 I realize the importance of compatibility but we're talking about ancient MPEG codecs and an issue from 2011 that we're not even sure is happening anymore

**Comment by bikeath1337** [comment]
I'm not following your response, @d4rky-pl . I think the gem should be corrected to place the screenshot input options before the input -- for the greatest compatibility and performance. I don't understand how this is related to [breaking] compatibility until i'm missing something subtle.

**Comment by d4rky-pl** [comment]
@bikeath1337 sorry, I didn't catch that we're actually agreeing on this 😳

**Comment by d4rky-pl** [comment]
@bikeath1337 the only problem I see now is that the `-ss` should be put before `-i` automatically only in case `screenshot` is set and the way Transcoder is implemented right now, putting things before `-i` is in `transcoder_options` while `screenshot` and `seek_time` are in `encoder_options` which brings us back to "maybe those two should be actually the same thing"

**Comment by bikeath1337** [comment]
@d4rky-pl The PR may not be the perfect solution, but I thought I would give it a try.
