### ISSUE TITLE
How can I remove the audio from the movie?

### ISSUE THREAD

**Issue by billzee** [streamio/streamio-ffmpeg#172]
I tried setting audio_channels to 0 but it still plays audio.

**Comment by bradcordeiro** [comment]
The FFMPEG option to remove audio from an output movie is "-an", try including that in the custom key of your encoding options.

Example:

```
options = {
    video_codec: "libx264",  resolution: "320x240", custom: ["-an"]
}

movie.transcode("movie.mp4", options)
```

**Comment by billzee** [comment]
Thank You. By the time I opened this issue, I was unaware of what could be done with this implementation of ffmpeg and that there was outside documentation about ffmpeg itself. Thanks again!
