### ISSUE TITLE
Error: cannot load such file -- streamio-ffmpeg

### ISSUE THREAD

**Issue by alexanderzatko** [streamio/streamio-ffmpeg#188]
I read the "Specify the path to ffmpeg" section and created a symlink for the ffmpeg installation. I can issue a command "man ffmpeg" and see the man page. Yet, I still see this error when trying to run my script from terminal:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- streamio-ffmpeg (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from testsm.rb:4:in `\<main\>

could somebody suggest what else should I try?

**Comment by alexanderzatko** [comment]
never mind. Running the **gem install streamio-ffmpeg** command after **brew install ffmpeg** solves this noob's problem

**Comment by Thomastar** [comment]
it must be Mac OS ?
