### ISSUE TITLE
is it can read remote video

### ISSUE THREAD

**Issue by imustardsoft** [streamio/streamio-ffmpeg#42]
I have a video stored in amazon s3.
Is this gem can read the video and make the video thumbnails?  

I just try 
<pre>
 movie = FFMPEG::Movie.new("https://s3.amazonaws.com/XXX/XXX.mp4")
</pre>

Seems don't work.

**Comment by dieuit07** [comment]
+1
Is it have anyway to read video before uploading to s3 directory? :)

**Comment by gmcnaughton** [comment]
Check out pull #130 and pull #121, both aim to add support for processing URLs instead of videos.  (I'm not sure whether this will work for processing the videos, or if it's just for extracting metadata about the video, e.g. duration and bitrate)

**Comment by d4rky-pl** [comment]
@gmcnaughton It will work with processing the video if your [ffmpeg is compiled with protocol support (it is by default)](https://www.ffmpeg.org/ffmpeg-protocols.html#Protocols).

**Comment by gmcnaughton** [comment]
@d4rky-pl good to know - thank you!

**Comment by bikeath1337** [comment]
URL inputs are now supported.

**Comment by mhluska** [comment]
@bikeath1337 it looks like only URLs without query params are supported. The gem seems to toss away the query part which may result in 403 errors for Amazon S3 resources where the auth token is part of the query param.

**Comment by abidiqbalk** [comment]
I am still unable to get meta info from s3 url using the gem. Can anyone help me sort this out?

Thanks
