### ISSUE TITLE
video_stream regex misses some Quicktime videos

### ISSUE THREAD

**Issue by innonate** [streamio/streamio-ffmpeg#51]
https://github.com/streamio/streamio-ffmpeg/blob/master/lib/ffmpeg/movie.rb#L46

This doesn't quite work with every video stream and could probably be more sophisticated (I may get around to it, but putting up here in case any one else wants to take a stab).

I have a video exported from an old iMovie version. It's video stream value is:

`none (icod / 0x646F6369), 960x540, 18653 kb/s): unknown codec`

This causes the `resolution` to be `18653` resulting in a height of `0` and width of `18653`

May be better to extract resolution separately with a regex like `(\d{1,})x(\d{1,}),`

**Comment by bikeath1337** [comment]
We now support checking for invalid/unsupported streams.
