### ISSUE TITLE
Return Metadata

### ISSUE THREAD

**Issue by alexis779** [streamio/streamio-ffmpeg#56]
I can't find an accessor to custom metadata, such as "date" (although we do have "creation_time"), which is the moment when the user actually shot the video.

    irb> local_path = "/home/alexis2/Downloads/IMG_0980.MOV"
    irb> movie = FFMPEG::Movie.new(local_path)
    => #<FFMPEG::Movie:0x000000010c5c28 @path="/home/alexis2/Downloads/IMG_0980.MOV", @duration=14.76, @time=0.0, @creation_time=2013-05-31 00:00:05 -0700, @bitrate=809, @rotation=nil, @video_stream="h264 (Main), yuv420p, 480x272, 742 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc", @audio_stream="aac, 44100 Hz, mono, s16, 62 kb/s", @video_codec="h264 (Main)", @colorspace="yuv420p", @video_bitrate=742, @resolution="480x272", @audio_codec="aac", @audio_channels="mono", @audio_bitrate=62, @audio_sample_rate=44100>

whereas

    $ ffmpeg -i /home/alexis2/Downloads/IMG_0980.MOV
    Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2013-05-31 00:00:05
    encoder         : 6.1.4
    encoder-eng     : 6.1.4
    date            : 2013-05-27T19:43:59-0700
    date-eng        : 2013-05-27T19:43:59-0700
    Duration: 00:00:14.76, start: 0.000000, bitrate: 809 kb/s

which has a **date** info I'm interested in. Not interested in **creation_time** in my app.

**Comment by bikeath1337** [comment]
All metadata from ffprobe is available in the Movie's `metadata` attribute as of 2.1.0.
