### ISSUE TITLE
Enable multiple screenshots via allowing to use array in `seek_time`

### ISSUE THREAD

**Issue by paazmaya** [streamio/streamio-ffmpeg#62]
Enable to use `seek_time` option of the `screenshot` method  as an array of floats, so that in the case of taking several screenshots of the same video, they can be done in one call.

**Comment by bikeath1337** [comment]
This is supported with the enhanced screenshot feature.

**Comment by paazmaya** [comment]
Um... Thanks

**Comment by bikeath1337** [comment]
In spite of the delay, which is why I assume you wrote "umm...", I hope you think I did the right thing by cleaning up and replying.

**Comment by paazmaya** [comment]
It was the right :calling:
