### ISSUE TITLE
Thumbnailing & watermarking

### ISSUE THREAD

**Issue by airy** [streamio/streamio-ffmpeg#8]
thanks for great gem.

would you like to add thumbnail and watermark support?

there are some links i found:

http://www.corbellconsulting.com/2010/07/using-ffmpeg-to-add-and-watermark-overlay-on-a-video-2/

http://blog.prashanthellina.com/2008/03/29/creating-video-thumbnails-using-ffmpeg/

edit: ops i missed this: https://github.com/streamio/streamio-ffmpeg/issues/unreads#issue/6

**Comment by bikeath1337** [comment]
ffmpeg supports both thumbnail and watermark features.
