### ISSUE TITLE
Start time offset

### ISSUE THREAD

**Issue by ifeatu** [streamio/streamio-ffmpeg#81]
When I run --
    system( "ffmpeg -y -ss 10505.89 -t 10 -i video/test-meeting.m4v -ab 192000 tmp/output.m4v" )
completion time is less than a second.

When I run --
    options = { custom: "-ss 10505.89 -t 10"  }
    transcoder_options = { custom: "-ab 192000"}
    @transcoded_movie = service.transcode( "tmp/movie.m4v", options, transcoder_options )

it takes minutes...or more.  Is there a reason for this?

**Comment by infoman** [comment]
Would like to see faster screenshots too

**Comment by bikeath1337** [comment]
FFMpeg binary has optimized this as well. The gem supports explicitly applying input_options as of 2.1.0.

**Comment by khalilfazal** [comment]
Why is this closed? Issue is still reproducible for me using streamio-ffmpeg-3.0.2. Is there a relevant pull request? I'll use bikeath1337's fork for now.
