### ISSUE TITLE
Add timecode reading

### ISSUE THREAD

**Issue by GeorgesLeYeti** [streamio/streamio-ffmpeg#83]
Hi,

I'm very new to RoR and i want to make an app where i have to convert some audio file and read meta. 
So i found your very interesting gem. In some of these audio files there is a meta data call: timecode which indicate the starting time of this audio file.
Is it possible to add this meta? So here what i would like to add in movie.rb

attr_reader :timecode

output[/timecode {1,}: {1,}(\d{2}):(\d{2}):(\d{2}):(\d{2})/]
@timecode = ($1.to_i*60*60) + ($2.to_i*60) + $3.to_i

Btw, the timecode is HH:MM:SS:frame don't know to use the fram so i ignored it.

**Comment by GeorgesLeYeti** [comment]
I don't how it works but i made a fork and it works great.

**Comment by bikeath1337** [comment]
The Movie's metadata is available as an attribute as of 2.1.0.
